version: '3.8'

services:
  web:
    build: .
    ports:
      - "5959:5858"
    volumes:
      - /opt/event_demo_app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5858
      - HOST=0.0.0.0
    command: flask run --host=0.0.0.0 --port=5858 --debug
    restart: unless-stopped
